package io.github.mszajner.beanboot.setup;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;

@Service
class SetupService {

    private static final Logger log = LoggerFactory.getLogger(SetupService.class);

    @Value("${app.config-file}")
    private String configFilePath;

    /**
     * Tests the JDBC connection described by {@code form}.
     * If successful, writes the configuration to the external application.properties file.
     *
     * @throws SQLException if the connection cannot be established
     * @throws IOException  if the config file cannot be written
     */
    void testAndSave(SetupForm form) throws SQLException, IOException {
        String url = buildJdbcUrl(form);
        log.info("Testing database connection: {}", url);
        try (Connection conn = DriverManager.getConnection(url, form.getUsername(), form.getPassword())) {
            log.info("Connection OK – database product: {}", conn.getMetaData().getDatabaseProductName());
        }
        saveConfig(form);
        log.info("Configuration written to: {}", configFilePath);
    }

    private String buildJdbcUrl(SetupForm form) {
        return switch (form.getConnection().toUpperCase()) {
            case "MSSQL" -> "jdbc:sqlserver://" + form.getHost() + ":" + form.getPort()
                    + ";databaseName=" + form.getDatabase()
                    + ";encrypt=true;trustServerCertificate=true";
            case "PGSQL" -> "jdbc:postgresql://" + form.getHost() + ":" + form.getPort()
                    + "/" + form.getDatabase();
            case "MYSQL" -> "jdbc:mysql://" + form.getHost() + ":" + form.getPort()
                    + "/" + form.getDatabase();
            default -> throw new IllegalArgumentException(
                    "Nieznany typ bazy danych: " + form.getConnection());
        };
    }

    private void saveConfig(SetupForm form) throws IOException {
        Properties props = new Properties();
        props.setProperty("db.connection", form.getConnection().toLowerCase());
        props.setProperty("db.host", form.getHost());
        props.setProperty("db.port", String.valueOf(form.getPort()));
        props.setProperty("db.database", form.getDatabase());
        props.setProperty("db.username", form.getUsername());
        props.setProperty("db.password", form.getPassword());

        Path target = Path.of(configFilePath);
        if (target.getParent() != null) {
            Files.createDirectories(target.getParent());
        }
        try (Writer writer = Files.newBufferedWriter(target)) {
            props.store(writer, "Database configuration – generated by setup wizard");
        }
    }
}
